
services:
  burgerorderer:
    image: burgerorderer
    build: ./Containers/BurgerOrderer
    ports:
      - 8000:8000
    volumes:
      - ./Containers/BurgerOrderer:/app
    environment:
      KITCHENVIEW_HOST: 'kitchenview:5000'

  kitchenview:
    image: kitchenview
    build: ./Containers/KitchenView
    ports:
      - 5000:5000
    volumes:
      - ./Containers/KitchenView:/app
  
  menustore:
    image: menustore
    build: ./Containers/menustore
    ports:
      - 6000:6000
    volumes:
      - ./Containers/menustore:/app
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
      DATABASE_URL: 'postgresql://your_username:your_password@localhost:5432/your_database_name'
