
services:
  burgerorderer:
    image: burgerorderer
    build: ./Containers/BurgerOrderer
    ports:
      - 8000:8000
    volumes:
      - ./Containers/BurgerOrderer:/app
    environment:
      KITCHENVIEW_HOST: 'kitchenview:5000'

  kitchenview:
    image: kitchenview
    build: ./Containers/KitchenView
    ports:
      - 5000:5000
    volumes:
      - ./Containers/KitchenView:/app
  
  MenueStore:
    image: Menuestore
    build: ./Containers/MenueStore
    ports:
      - 6000:6000
    volumes:
      - ./Containers/MenueStore:/app
